language: node_js
node_js:
  - "8.14.0"

branches:
  only:
    - uc_4_testing

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: www
