language: node_js
node_js:
  - "8.14.0"
  
addons:
  chrome: stable

branches:
  only:
    - test
    
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    
before_script:
  - npm install -g ionic cordova
  - npm install

script:
  - node_modules/karma/bin/karma start ./test-config/karma.conf.js --single-run
  - ionic cordova build browser --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: test
  local_dir: www
